title: "askDomainer.com"
description: "Elevate Your Business with Expert Domain Acquisition, Sales, and Custom Software Development Tailored to Your Growth Journey."
mermaid:
  src: "mermaid.js"
plugins:
  - "jekyll-github-metadata"
  - "jekyll-readme-index"
readme_index:
  enabled:          true
  remove_originals: false
  with_frontmatter: false