name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install build tools
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Create virtual environment
      run: python3 -m venv ${{ runner.temp }}/venv

    - name: Activate virtual environment
      run: source ${{ runner.temp }}/venv/bin/activate

    - name: Check for requirements.txt
      run: |
        if [ ! -f requirements.txt ]; then
          echo "requirements.txt not found"
          exit 1
        fi

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: Install Ruby dependencies
      run: bundle install

    - name: Build Jekyll site
      run: bundle exec jekyll build